name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: npm i

      - name: Build app
        run: npm run build

      - name: Install serve
        run: npm i -g pm2

      - name: Run e2e tests
        uses: cypress-io/github-action@v5
        with:
          start: pm2 serve dist 3000 --spa
          build: npm run build
          command: npm e2e:ci
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          spec: tests/e2e/specs/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          NETWORK_NAME: mainnet
